# Site settings
title: Benjy Stanton
email: benjystanton@gmail.com
description: UX Designer. Family Man. Music Snob.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.benjystanton.co.uk" # the base hostname & protocol for your site
twitter_username: benjystanton
github_username:  benjystanton
dribbble_username:  benjystanton
instagram_username:  benjystanton

# Build settings
markdown: kramdown

# Outputting
permalink: /blog/:title/ # change default permalink structure to /blog/title-of-blog.html
post_dirs: true

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
